### ISSUE TITLE
Close folders

### ISSUE THREAD

**Issue by ghost** [quodroc/HumbleNewTabPage#28]
Auto-close folders is not working for me. I install it today. The first few hours it worked but then it stopped.
I have google-chrome version: 40.0.2209.0 dev (64-bit)

**Comment by afrey15** [comment]
It appears that this issue has been fixed. Unselect option "Remember open folders" and select option "Auto-close folders" Thank you developer!!

**Comment by quodroc** [comment]
I'll try to improve the wording in the options so it's more clear what they do.
