### ISSUE TITLE
Move bookmark back into folder

### ISSUE THREAD

**Issue by nkoep** [quodroc/HumbleNewTabPage#31]
I accidently moved a bookmark subfolder out of the "bookmarks bar" folder and added it to another column. Unfortunately, I'm now unable to move the folder back into the bookmarks folder.

**Comment by quodroc** [comment]
It's unintuitive but you can right-click the folder and choose "Remove folder" to restore its original position (or if it is the only folder in a column, right-click the column and choose "Remove column"). 

Also I recommend turning on the "Lock columns" option after you get everything set up the way you want to avoid moving things around by accident.

**Comment by nkoep** [comment]
Ahh, thanks for clearing that up.
