### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by lnalex** [quodroc/HumbleNewTabPage#33]
Due to issue #27 ,

I'm tracking for Firefox compatibility. Lot of users are waiting for it and will be grateful !

**Comment by quodroc** [comment]
This will be a lot easier when Firefox implements the [WebExtensions API](https://wiki.mozilla.org/WebExtensions), which is mostly compatible with Chrome's extension API. Unfortunately it isn't likely to be finished any time soon. Still, I'm considering just going ahead with the existing Firefox Add-on SDK.

**Comment by tech189** [comment]
Has there been any progress on this, or are we still waiting for webextensions?

**Comment by quodroc** [comment]
Sorry I haven't had any time to work on this. Still hoping for webextensions but it's moving pretty slow.

You may want to try the following addon: https://addons.mozilla.org/en-US/firefox/addon/bookrect/
It's not exactly the same but very similar.

**Comment by tech189** [comment]
Don't worry, thanks!

**Comment by andreicristianpetcu** [comment]
Hi all! I made [a port](https://andreicristianpetcu.github.io/chrome2firefox/addons/humble_new_tab_page-1.21-an+fx-windows.xpi) to Firefox with [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/). It does not work yet in Firefox stable but it does in [Nightly](https://www.mozilla.org/en-US/firefox/nightly/all/). I did not test Beta or DevEdition but usually WebExtension APIs have been riding the release trains to probably it will work really soon in stable.

Please [submit an official version](https://addons.mozilla.org/en-US/developers/addon/submit/distribution) to [AMO](https://addons.mozilla.org/ro/firefox/). It's the only thing you need to do.

**Comment by rohit1347** [comment]
Your extension is great, please make it compatible with firefox.

**Comment by quodroc** [comment]
Working on it. Currently the drag and drop is broken for some reason, and I need to disable a few things that don't work in Firefox (apps, other devices, and system font list).

**Comment by vecdot** [comment]
Thanks @quodroc, looking forward to your port! I've been following this thread since I made the switch to FF 57. Your extension is the one thing I'm missing from Chromium.

**Comment by quodroc** [comment]
Firefox version is now available at https://addons.mozilla.org/firefox/addon/humble-new-tab/
Compared to the Chrome version it is missing a few features:
- No apps
- No other devices
- No system font list
- No "edit bookmarks" and "clear browsing data" context menu items (https://bugzilla.mozilla.org/show_bug.cgi?id=1269456)
- file:/// and chrome:// URLs will not open (https://bugzilla.mozilla.org/show_bug.cgi?id=1269456)
- Website favicons are loaded through Google (https://bugzilla.mozilla.org/show_bug.cgi?id=1315616)

Please report any other bugs you may find, as I haven't tested it extensively.
