### ISSUE TITLE
localStorage import/export to plain text file

### ISSUE THREAD

**Issue by MetaMemoryT** [quodroc/HumbleNewTabPage#34]
At one point I lost my customization's,  would be happy to just manually export my settings, and import later if something messes up.

**Comment by quodroc** [comment]
For now you can copy the file 
`(chrome-profile)/Local Storage/chrome-extension_mfgdmpfihlmdekaclngibpjhdebndhdj_0.localstorage`

eg `C:\Users\user\AppData\Local\Google\Chrome\User Data\Default\Local Storage\chrome-extension_mfgdmpfihlmdekaclngibpjhdebndhdj_0.localstorage`

(go to chrome://version/ to find your profile path)

Make sure Chrome is closed when restoring a backup.

**Comment by MetaMemoryT** [comment]
Thanks!

**Comment by quodroc** [comment]
This has been added in version 1.20, Import/Export tab in the options. May revisit in the future to add download/input from file instead of copy/paste.
