### ISSUE TITLE
Recently Closed not respecting number of items settings

### ISSUE THREAD

**Issue by Nxt3** [quodroc/HumbleNewTabPage#36]
I'm on Chrome v51--so I realize this isn't HNTP's fault.

I have my number of items in Recently Closed set to 5--yet, I have 25 showing up in the list right now. The list grows and grows--disregarding the limit in Settings.

**Comment by quodroc** [comment]
The chrome.sessions API seems to be ignoring the maxResults parameter. I could add a failsafe to limit the items regardless of how many the API returns.

**Comment by turmoggy** [comment]
Its nearly june and I'm experiencing this bug as well. I'm using the official build.

**Comment by quodroc** [comment]
Fixed in version 1.20 (ed982a2)

**Comment by Nxt3** [comment]
Thank you! :)
