### ISSUE TITLE
How do I split the bookmarks horizontally ?

### ISSUE THREAD

**Issue by wealstarr** [quodroc/HumbleNewTabPage#53]
Hello, 

First off awesome! Tried literally hundreds of speed dial addons but found yours to match exactly my taste.
Now the question. All my bookmarks are placed vertically and I have to scroll way too much to reach the sites as the list is quite long so how do I split them horizontally ? say in two or three columns. Like the previews on the Mozilla addons page.
All my bookmarks are in one folder and I don't use weather.  

Any help will be greatly appreciated. And thanks for this awesome addon. Great work!

Regards.

**Comment by quodroc** [comment]
It's not currently a feature, the screenshots use different folders for each column.
You could try the following in Advancd > Custom CSS
`.column:first-child { column-count: 2; }`
Assuming you want to split the first column. But it might have some weird behaviour when you open or close subfolders.

**Comment by wealstarr** [comment]
Thanks for the quick response. yeah that did it, and no weird behaviors as I don't have any sub-folders. It's just one list in one single folder. Everything works fine.

Just one more thing. Is it possible to change the favicons/icons for the bookmarks from local hard drive ?
Lot's of sites I've pinned don't even use favicons and the rest are taking ample time to load as the list is quite long.

Thanks for the support, your contribution is greatly appreciated quodroc.

**Comment by quodroc** [comment]
Not at the moment but I am planning to add that feature at some point.

**Comment by wealstarr** [comment]
That would be a much needed addition. Apart from that it all works very smoothly. I'll keep an eye on the updates.

Thanks again.
