### ISSUE TITLE
[Feature request] Change extension name shown in address bar to HNTP

### ISSUE THREAD

**Issue by danielmmmm** [quodroc/HumbleNewTabPage#64]
Is it possible to leave the extension name in "about:addons" as is (Humble New Tab Page), but change the name in the address bar to HNTP?

On narrow screens, opening a new tab makes it difficult/impossible to access the address bar because most space is being used by Firefox displaying "Extension (Humble New Tab Page)".

In times of wide screens, this might not seem important. However, it can become a problem on smaller secondary displays or in small Firefox windows.

**Comment by quodroc** [comment]
Not a bad idea. There is an open request in the Firefox bug tracker to use the extension short_name in the address bar: https://bugzilla.mozilla.org/show_bug.cgi?id=1477800

I'll see if it's possible to have the address bar show HNTP, but still have it listed as "Humble New Tab Page" at addons.mozilla.org

**Comment by quodroc** [comment]
I changed the extension name to "HNTP" in today's update, should save some space in the address bar.

**Comment by danielmmmm** [comment]
I noticed :-)
Thanks a lot!
