### ISSUE TITLE
[Feature] Add Google Apps Dots which are present on all google webpages.

### ISSUE THREAD

**Issue by ectoanonymous** [quodroc/HumbleNewTabPage#71]
I love this extension and use it on daily basis.
It have everything which satisfies my needs but one thing....I always feels lack of those dots which are present on all google pages in which all google apps are present like contacts,gmail,youtube,maps & all other useful google services.

So. my request is this "please add those Google Dots to your Humble page"
Thank you.
![Screenshot (41)](https://user-images.githubusercontent.com/46634359/54877858-59a45880-4e4a-11e9-8853-e02b45486b17.png)

**Comment by quodroc** [comment]
It isn't possible to embed their menu into another webpage or extension, and I don't think trying to recreate it is worth the effort.

**Comment by ectoanonymous** [comment]
I thought you abandoned the project, btw I don't use this extension anymore.
I really had a great experience with your extension,

**Comment by quodroc** [comment]
Not abandoned, just slow moving :)

**Comment by ectoanonymous** [comment]
All the best for your extension😊, I'd recommend this to all my friends, after all it was the only extension which was according to my needs.
