### ISSUE TITLE
Favicon caching and Privacy

### ISSUE THREAD

**Issue by TCB13** [quodroc/HumbleNewTabPage#84]
Hello,

Thank you for this great extension that actually makes browsers right. I've a question somehow related to #60.

When does this extension fetch the favicons? Does it access all the bookmarks that are visible every single time I open a new tab? Does it cache them for some time? How does it work?

I don't want to do a request to all those websites everytime a new tab is open because they might use it to for tracking, currently I have the feature disabled but I would like to use it.

Thank you.

**Comment by quodroc** [comment]
Yes it fetches icons for all the visible bookmarks. The browser decides how long to cache them based on the cache headers sent by the server, same as any normal image. Only the domain is sent though, not the full URL.

If it helps I just added DuckDuckGo as an alternative icon provider. https://duckduckgo.com/privacy

**Comment by TCB13** [comment]
Thank you for the clarification.
